-- A run records every change row in one transaction, so its rows share a
-- created_at and the random uuid id orders nothing. The identity sequence
-- gives each row the order it was recorded in, within a run and across runs.
-- The table is append-only, so the values the upgrade fills existing rows with
-- in physical order are the order they were inserted in.
alter table reconciliation_changes
  add column recorded_seq bigint generated by default as identity;
