"""Exact Footer and filed-bug pointers are checked through the real gate."""
import html
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _util
from _prgate import (
    ROOT, _api, _gate_module, _html_body, _issue, _issue_gets, _issue_html,
    _text_html, _valid_body, _valid_html,
)

TEMPLATE = (ROOT / '.github/PULL_REQUEST_TEMPLATE.md').read_text(encoding='utf-8')
FOOTER = 'Generated by GPT-6 Astra (implementer)'


def _case(footer=FOOTER, bugs=None, *, issues=None):
    source = _valid_body()
    rendered = _valid_html()
    if bugs is not None:
        source += '\n## Bugs Discovered\n\n' + bugs + '\n'
        entries = ''.join('<li>' + html.escape(line.removeprefix('- ')) + '</li>'
                          for line in bugs.splitlines())
        rendered += _html_body(('Bugs Discovered', '<ul>' + entries + '</ul>'))
    source += '\n## Footer\n\n' + footer + '\n'
    rendered += _html_body(('Footer', _text_html(footer)))
    api = _api(rendered=rendered, issues=issues)
    api.pull['body'] = source
    return api


def _run(api):
    return _gate_module().run(api, 'owner/repo', '99', 'alice', TEMPLATE)


def test_footer_accepts_one_final_attribution_with_multiple_models_and_roles(tmp):
    del tmp
    for footer in (FOOTER, 'Generated by GPT-6 Astra (implementation, testing), '
                   'Claude Opus 4.8 (review)'):
        api = _case(footer)
        assert _run(api) == 0
        assert api.pull['state'] == 'open' and api.writes == [], footer


def test_footer_rejects_wrong_shape_multiple_lines_and_trailing_content(tmp):
    del tmp
    invalid = (
        'Not an attribution.', 'Generated via GPT-6 Astra (implementer)',
        'Generated by GPT-6 Astra ()', 'Generated by GPT-6 Astra (review,)',
        'Generated by (review)', FOOTER + '\n' + FOOTER,
        FOOTER + '\nMore context.', ' ' + FOOTER, FOOTER + ' ',
        '`' + FOOTER + '`', FOOTER + '\n<!-- hidden note -->',
        'Generated by \u200b (review)', 'Generated by \u034f (review)',
        'Generated by GPT-6 Astra (\u2800)',
        'Generated by GPT-6\u2028Astra (review)',
    )
    for footer in invalid:
        api = _case(footer)
        assert _run(api) == 0
        assert api.pull['state'] == 'closed', footer
        assert 'Footer' in api.comments[0]['body'], footer


def test_bugs_accept_only_existing_issue_pointers_with_exact_titles(tmp):
    del tmp
    api = _case(bugs='- #104 Fix `parse()` & validation\n- #105 Another bug', issues={
        '101': _issue('alice'),
        '104': {**_issue('bob'), 'title': 'Fix `parse()` & validation'},
        '105': {**_issue(), 'title': 'Another bug'},
    })
    assert _run(api) == 0
    assert api.pull['state'] == 'open' and api.writes == []
    assert [call[1] for call in _issue_gets(api)] == [
        'repos/owner/repo/issues/101', 'repos/owner/repo/issues/104',
        'repos/owner/repo/issues/105']


def test_bugs_reject_narrative_and_non_pointer_list_entries(tmp):
    del tmp
    for bugs in ('Unfiled bug narrative.', '- No issues.', '* #104 The bug',
                 '- #104', '- #0 The bug', '- #104 The bug\nExplanation.',
                 '- [#104](https://github.com/owner/repo/issues/104) The bug',
                 '  - #104 The bug', '- #104 The bug\n\n- extra context',
                 '```\n- #104 The bug\n```'):
        api = _case(bugs=bugs, issues={
            '101': _issue('alice'), '104': {**_issue(), 'title': 'The bug'}})
        assert _run(api) == 0
        assert api.pull['state'] == 'closed', bugs
        assert 'Bugs Discovered' in api.comments[0]['body']


def test_bugs_reject_missing_issues_pull_requests_and_nonliteral_titles(tmp):
    del tmp
    for issue in (None, {**_issue(pull_request=True), 'title': 'The bug'},
                  {**_issue(), 'title': 'the bug'}, {**_issue(), 'title': 'The bug!'}):
        issues = {'101': _issue('alice')}
        if issue is not None:
            issues['104'] = issue
        api = _case(bugs='- #104 The bug', issues=issues)
        assert _run(api) == 0
        assert api.pull['state'] == 'closed', issue
        assert 'Bugs Discovered' in api.comments[0]['body']


def test_bugs_lookup_failures_abort_before_any_write(tmp):
    del tmp
    api = _case(bugs='- #104 The bug')
    api.fail.add('GET repos/owner/repo/issues/104')
    assert _run(api) == 1
    assert api.writes == [] and api.pull['state'] == 'open'


def test_bug_pointers_share_the_twenty_reference_budget_and_issue_cache(tmp):
    del tmp
    api = _case(bugs='- #101 The bug', issues={
        '101': {**_issue('alice'), 'title': 'The bug'}})
    assert _run(api) == 0 and api.writes == []
    assert len(_issue_gets(api)) == 1

    numbers = range(101, 121)
    references = '\n'.join(f'References #{number}' for number in numbers)
    api = _case(bugs='- #999 Unchecked bug', issues={
        str(number): _issue('alice') for number in numbers})
    api.pull['body'] = api.pull['body'].replace('Fixes #101', references)
    api.rendered = api.rendered.replace(
        f'Fixes {_issue_html(101)}',
        '\n'.join(_issue_html(number) for number in numbers))
    assert _run(api) == 0
    assert len(_issue_gets(api)) == 20
    assert 'more than 20 issue references' in api.comments[0]['body']


def test_content_contract_accepts_supported_heading_spellings(tmp):
    del tmp
    for footer_heading in (
            '### Footer', '## **Footer**:', '<h2>Footer</h2>',
            '<h2 title="1 > 0"><em>Footer</em></h2>',
            '## ![Footer](footer.png)', '## <img src="f.png" alt="Footer">'):
        api = _case()
        api.pull['body'] = api.pull['body'].replace('## Footer', footer_heading)
        assert _run(api) == 0
        assert api.writes == [], footer_heading


def test_heading_examples_in_fences_and_comments_do_not_redefine_content(tmp):
    del tmp
    for example in ('```markdown\n## Footer\n## Bugs Discovered\n```',
                    '<!--\n## Footer\n## Bugs Discovered\n-->'):
        api = _case(bugs='- #104 The bug', issues={
            '101': _issue('alice'), '104': {**_issue(), 'title': 'The bug'}})
        api.pull['body'] = api.pull['body'].replace(
            '- One change', example + '\n\n- One change')
        api.rendered = api.rendered.replace(
            '<ul dir="auto">\n<li>One change</li>\n</ul>',
            '<pre><code>' + html.escape(example) + '</code></pre>'
            '<ul><li>One change</li></ul>')
        assert _run(api) == 0
        assert api.writes == [], example


if __name__ == '__main__':
    raise SystemExit(_util.runner(_util.collect(globals()), tmp_prefix='prcontent_'))
