#!/usr/bin/env python3
"""Admission behavior against Overflow's shipped pull-request contract."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _util
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
PR_BODY = _util.load(ROOT / 'scripts/ci/pr_body.py', 'scripts.ci.pr_body')


TEMPLATE = (ROOT / '.github/PULL_REQUEST_TEMPLATE.md').read_text(encoding='utf-8')


def _required_html():
    return ('<h2 dir="auto">Summary</h2>'
            '<p dir="auto">Check pull request admission.</p>'
            '<h2 dir="auto">Changes</h2><p>Add the gate.</p>'
            '<h2 dir="auto">Testing</h2><p>Ran the gate suites.</p>'
            '<h2 dir="auto">Footer</h2>'
            '<p>Generated by GPT-6 Astra (implementer)</p>')


def _required_body():
    return ('## Summary\n\nFixes #101\n\n'
            '## Changes\n\nAdd the gate.\n\n'
            '## Testing\n\nRan the gate suites.\n\n'
            '## Footer\n\nGenerated by GPT-6 Astra (implementer)\n')


def test_shipped_required_sections_are_enforced(tmp):
    del tmp
    assert PR_BODY.layout_errors((), TEMPLATE) == [
        'Required section "Summary" is missing.',
        'Required section "Changes" is missing.',
        'Required section "Testing" is missing.',
        'Required section "Footer" is missing.',
    ]


def test_conditional_and_optional_sections_can_be_omitted(tmp):
    del tmp
    sections = PR_BODY.parse_rendered(_required_html(), 'owner/repo').sections
    assert PR_BODY.layout_errors(sections, TEMPLATE) == []


def test_required_tag_recognition_is_case_insensitive(tmp):
    del tmp
    for tag in ('required', 'Required', 'REQUIRED', 'rEqUiReD'):
        template = f'## Summary\n<!-- {tag}. Explain the change. -->'
        assert PR_BODY.layout_errors((), template) == [
            'Required section "Summary" is missing.']


def test_conditional_and_optional_tags_are_case_insensitive(tmp):
    del tmp
    for tag in ('conditional', 'Conditional', 'CONDITIONAL',
                'optional', 'Optional', 'OPTIONAL'):
        template = f'## Details\n<!-- {tag}. Include when applicable. -->'
        assert PR_BODY.layout_errors((), template) == []
        empty = PR_BODY.parse_rendered('<h2>Details</h2>', 'owner/repo')
        assert PR_BODY.layout_errors(empty.sections, template) == [
            'Section "Details" is empty.']


def test_missing_footer_closes_and_corrective_edit_reopens(tmp):
    from _prgate import _api, _gate_module
    del tmp
    rendered = _required_html().replace(
        '<p dir="auto">Check pull request admission.</p>',
        '<p>Fixes <a href="https://github.com/owner/repo/issues/101">#101</a></p>')
    api = _api(rendered=rendered.split('<h2 dir="auto">Footer</h2>')[0])
    api.pull['body'] = _required_body().split('## Footer')[0]
    gate = _gate_module()
    assert gate.run(api, 'owner/repo', '99', 'alice', TEMPLATE) == 0
    assert api.pull['state'] == 'closed'
    assert 'Required section "Footer" is missing.' in api.comments[0]['body']
    api.rendered = rendered
    api.pull['body'] = _required_body()
    assert gate.run(api, 'owner/repo', '99', 'alice', TEMPLATE) == 0
    assert api.pull['state'] == 'open'
    assert len(api.comments) == 1


def test_a_layout_valid_body_still_needs_an_assigned_issue(tmp):
    from _prgate import _api, _gate_module
    del tmp
    api = _api(rendered=_required_html(), issues={})
    api.pull['body'] = _required_body().replace('Fixes #101', 'No related work.')
    assert _gate_module().run(api, 'owner/repo', '99', 'alice', TEMPLATE) == 0
    assert api.pull['state'] == 'closed'
    assert 'No checked issue is assigned to you.' in api.comments[0]['body']


def test_shipped_instruction_comments_are_rejected(tmp):
    del tmp
    assert PR_BODY.retains_instruction_comment(TEMPLATE, TEMPLATE)
    assert not PR_BODY.retains_instruction_comment(
        '## Summary\nA change.\n<!-- reviewer note -->', TEMPLATE)


if __name__ == '__main__':
    raise SystemExit(_util.runner(_util.collect(globals()), tmp_prefix='overflowgate_'))
