"""Literal attribution and filed-issue pointer contracts for PR sections."""
import re
from html.parser import HTMLParser
from unicodedata import category

if __package__:
    from .pr_body import _has_visible_text
else:
    from pr_body import _has_visible_text

_MARKDOWN_HEADING = re.compile(
    r'^[ \t]{0,3}#{1,6}[ \t]+(.+?)[ \t]*#*[ \t]*$', re.MULTILINE)
_HTML_HEADING = re.compile(
    r'^[ \t]{0,3}(<h[1-6](?:\s[^\n]*)?>[^\n]*</h[1-6]\s*>)[ \t]*$',
    re.MULTILINE | re.IGNORECASE)
_FENCE = re.compile(r'^[ \t]{0,3}(`{3,}|~{3,})(.*)$')
_LABEL = r'[^\s(),](?:[^(),\r\n]*[^\s(),])?'
_MODEL = rf'{_LABEL} \({_LABEL}(?:, {_LABEL})*\)'
_FOOTER = re.compile(rf'Generated by {_MODEL}(?:, {_MODEL})*')
_ATTRIBUTION = re.compile(r'([^(),]+) \(([^()]+)\)(?:, |$)')
_BUG = re.compile(r'- #([1-9][0-9]{0,18}) (\S(?:.*\S)?)')
FOOTER_ERROR = (
    'Footer must contain exactly one final line: '
    '`Generated by <model> (<role>, <role>, ...), <model> (<role>, ...)`.')
BUGS_ERROR = (
    'Bugs Discovered must contain only `- #N Literal issue title` pointers '
    'to existing issues, with each title copied exactly.')


def _mask(text):
    return ''.join('\n' if char == '\n' else ' ' for char in text)


class _HeadingText(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts = []

    def handle_data(self, data):
        self.parts.append(data)

    def handle_starttag(self, tag, attrs):
        if tag == 'img':
            self.parts.append(dict(attrs).get('alt') or '')


def _heading_key(text):
    text = re.sub(r'!?\[([^\]]*)\]\([^\n]*\)', r'\1', text)
    parser = _HeadingText()
    parser.feed(text)
    parser.close()
    text = re.sub(r'[*_~`]', '', ''.join(parser.parts))
    return ' '.join(text.split()).rstrip(':').casefold()


def _headings(source):
    # Heading-shaped examples and comments cannot redefine the section whose
    # literal content is checked. The rendered parser remains authoritative for
    # the actual section names, order, visibility, and structural validity.
    masked = re.sub(r'<!--.*?-->', lambda match: _mask(match[0]), source,
                    flags=re.DOTALL)
    lines = []
    fence = None
    for line in masked.splitlines(keepends=True):
        match = _FENCE.match(line.rstrip('\n'))
        if fence is not None:
            lines.append(_mask(line))
            if (match and match[1][0] == fence[0]
                    and len(match[1]) >= len(fence) and not match[2].strip()):
                fence = None
        elif match:
            fence = match[1]
            lines.append(_mask(line))
        else:
            lines.append(line)
    masked = ''.join(lines)
    matches = sorted(
        [*_MARKDOWN_HEADING.finditer(masked), *_HTML_HEADING.finditer(masked)],
        key=lambda match: match.start())
    return [(match.start(), match.end(), _heading_key(match[1]))
            for match in matches]


def _region(source, headings, key):
    positions = [index for index, (_, _, name) in enumerate(headings) if name == key]
    if len(positions) != 1:
        return None
    index = positions[0]
    end = headings[index + 1][0] if index + 1 < len(headings) else len(source)
    return source[headings[index][1]:end].strip('\n')


def section_content(source, sections):
    """Return content errors and literal (issue number, title) bug pointers."""
    source = source.replace('\r\n', '\n').replace('\r', '\n')
    headings = _headings(source)
    errors = []
    pointers = []
    for section in sections:
        if section.key not in ('footer', 'bugs discovered'):
            continue
        value = _region(source, headings, section.key)
        if section.key == 'footer':
            if (value is None or _FOOTER.fullmatch(value) is None
                    or len(value.splitlines()) != 1
                    or any(category(char).startswith('C') for char in value)
                    or not all(_has_visible_text(label)
                               for model, roles in _ATTRIBUTION.findall(
                                   value.removeprefix('Generated by '))
                               for label in (model, *roles.split(', ')))
                    or section.text.strip() != value
                    or not source.rstrip('\n').endswith(value)):
                errors.append(FOOTER_ERROR)
            continue
        lines = [line for line in (value or '').splitlines() if line.strip()]
        matches = [_BUG.fullmatch(line) for line in lines]
        if not lines or any(match is None for match in matches):
            errors.append(BUGS_ERROR)
            continue
        pointers.extend((int(match[1]), match[2]) for match in matches)
    return errors, pointers


def bug_issue_errors(pointers, records):
    errors = []
    for number, title in pointers:
        # Unchecked references are covered by the controller's shared bound.
        if number not in records:
            continue
        issue = records[number]
        if (issue is None or 'pull_request' in issue
                or issue.get('title') != title):
            errors.append(
                f'Bugs Discovered pointer `#{number}` must name an existing '
                'issue in this repository and copy its title exactly.')
    return errors
