/**
 * Every migration the schema suite expects to find applied, in name order.
 * `tests/db/schema.test.ts` asserts that `schema_migrations` holds exactly
 * these names, each once, so a new `db/migrations/NNN_*.sql` fails that suite
 * until it is named here too. Relocated from schema.test.ts so that file stays
 * under its recorded module-size ceiling (the check offers exactly two
 * remedies: shrink, or relocate into a new module).
 */
export const appliedMigrationNames: readonly string[] = [
  "001_initial.sql",
  "002_repository_difficulty_scheme.sql",
  "003_multi_issue_settlements_and_claims.sql",
  "004_preserve_reconciliation_provenance.sql",
  "005_harden_materialization_invariants.sql",
  "006_account_moderation_snapshots.sql",
  "007_authoritative_history_and_merge_proof.sql",
  "008_moderator_role_changes.sql",
  "009_settlement_override_requests.sql",
  "010_settled_evidence_ordering_grace.sql",
  "011_api_tokens.sql",
  "012_unwritable_closure_kinds.sql",
  "013_immutable_github_identity.sql",
  "013_reconciliation_cooldown.sql",
  "014_opening_authority_precondition.sql",
  "015_normalize_settlement_status_check.sql",
  "016_repository_identity_verification.sql",
  "017_cross_repository_closures.sql",
  "018_refreshable_display_logins.sql",
  "019_recorded_materialization_removals.sql",
  "020_repository_reconciliation_jobs.sql",
  "021_reconciliation_lease_duration.sql",
  "022_fold_revision_stamps.sql",
  "023_rederivation_requests.sql",
  "024_reconciliation_run_rederivation.sql",
  "025_rederivation_generation.sql",
  "026_incremental_reconciliation.sql",
  "027_issue_github_updated_at.sql",
  "028_repository_reconciliation_cost.sql",
  "029_reconciliation_changes_recorded_seq.sql",
  "030_repository_difficulty_scheme_versions.sql",
  "031_tighten_issue_evidence_completeness.sql",
  "032_immutable_claim_assignee_identity.sql",
  "033_self_work_calibrations_issue_unique.sql",
  "034_repository_unregistration.sql",
  "035_moderation_credit_adjustments.sql",
  "036_override_reconciliation_reason.sql",
  "037_abandoned_webhook_cleanups.sql",
  "038_forge_identities_and_provider_columns.sql",
  "039_forge_identity_user_fk.sql",
  "040_forge_repository_columns.sql",
  "041_forge_identity_token_failed_at.sql",
  "042_gitlab_webhook_orphan_cleanup.sql",
  "043_repository_webhook_credentials.sql",
  "044_completed_work_credit_limits.sql",
  "045_account_pseudonymisation.sql",
  "046_api_token_expiry.sql",
  "048_unregistered_webhook_credentials.sql",
  "049_reason_length_limits.sql",
  "051_forge_identity_https_instance.sql",
  "052_repository_policy_violations.sql",
  "053_webhook_delivery_receipt_scope.sql",
  "054_privileged_action_credentials.sql",
  "055_allow_nullable_issue_and_pr_bodies.sql",
  "056_board_read_indexes.sql",
  "057_fold_evidence_facts.sql",
  "058_api_token_delivery_window.sql",
  "059_session_epoch.sql",
  "060_sanction_deactivation_flag.sql",
  "061_sanction_contest_requests.sql",
  "062_webhook_delivery_body_digest.sql",
  "063_null_avatar_urls.sql",
];
