#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { THIRD_PARTY_LICENCE_TEXTS } from "./third-party-licence-texts.ts";

export interface NoticeEntry {
  name: string;
  version: string;
  license: string;
  homepage?: string;
  directory: string;
}

export type NoticeResult = { ok: true; text: string } | { ok: false; missing: string[] };

type ReadLicenceFile = (directory: string) => string | undefined;

function licenceFileRank(name: string): number | undefined {
  const lower = name.toLowerCase();
  if (lower === "license" || lower === "licence") return 0;
  if (lower.startsWith("license") || lower.startsWith("licence")) return 1;
  if (lower.startsWith("copying")) return 2;
  if (lower.startsWith("notice")) return 3;
  if (lower.startsWith("copyright")) return 4;
  return undefined;
}

export function readLicenceFile(directory: string): string | undefined {
  let names: string[];
  try {
    names = readdirSync(directory);
  } catch {
    return undefined;
  }
  const matches = names.filter((name) => licenceFileRank(name) !== undefined);
  matches.sort((a, b) =>
    (licenceFileRank(a) ?? 5) - (licenceFileRank(b) ?? 5) ||
    a.length - b.length || a.toLowerCase().localeCompare(b.toLowerCase()),
  );
  const first = matches[0];
  if (first) {
    try {
      return readFileSync(join(directory, first), "utf8");
    } catch {
      return undefined;
    }
  }
  return undefined;
}

export function buildNotices(entries: NoticeEntry[], readLicenceFile: ReadLicenceFile): NoticeResult {
  const missing: string[] = [];
  const groups = new Map<string, Array<NoticeEntry & { canonical: boolean }>>();
  for (const entry of entries) {
    const label = `${entry.name}@${entry.version}`;
    if (!entry.license?.trim() || /^unknown$/i.test(entry.license.trim())) {
      missing.push(label);
      continue;
    }
    const shippedText = readLicenceFile(entry.directory);
    const canonical = !shippedText?.trim();
    const text = canonical ? THIRD_PARTY_LICENCE_TEXTS[entry.license] : shippedText;
    if (!text?.trim()) {
      missing.push(label);
      continue;
    }
    const group = groups.get(text) ?? [];
    group.push({ ...entry, canonical });
    groups.set(text, group);
  }
  if (missing.length) return { ok: false, missing: [...new Set(missing)].sort() };

  const sections = [...groups.entries()].map(([text, packages]) => {
    const rows = packages
      .sort((a, b) => `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`))
      .map((entry) =>
        `- ${entry.name}@${entry.version}\n  Licence: ${entry.license}` +
        (entry.homepage ? `\n  Homepage: ${entry.homepage}` : "") +
        (entry.canonical
          ? `\n  Licence file: none shipped — canonical text of declared licence (${entry.license})`
          : ""),
      );
    return `Packages:\n${rows.join("\n")}\n\nFull licence text:\n${text}`;
  });
  const header =
    "Third-party notices\n" +
    "Generated at build time from the production dependency tree using " +
    "pnpm licenses list --prod --json.\n" +
    "Do not edit this file; rebuild it from the dependency tree.\n";
  return { ok: true, text: `${header}\n${sections.join("\n\n---\n\n")}\n` };
}

interface PnpmEntry {
  name: string;
  versions: string[];
  paths: string[];
  license?: string;
  homepage?: string;
}

function flattenPnpmOutput(raw: unknown): NoticeEntry[] {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("pnpm licence output is not a licence-to-packages map");
  }
  const entries: NoticeEntry[] = [];
  for (const [license, group] of Object.entries(raw)) {
    if (!Array.isArray(group)) throw new Error(`pnpm licence group ${license} is not a list`);
    for (const item of group as PnpmEntry[]) {
      if (!item || typeof item.name !== "string" || !Array.isArray(item.versions) ||
          !Array.isArray(item.paths) || item.versions.length !== item.paths.length ||
          item.versions.length === 0) {
        throw new Error(`invalid package entry in pnpm licence group ${license}`);
      }
      for (let index = 0; index < item.versions.length; index += 1) {
        const version = item.versions[index];
        const directory = item.paths[index];
        if (typeof version !== "string" || typeof directory !== "string") {
          throw new Error(`invalid version or path for ${item.name}`);
        }
        entries.push({
          name: item.name,
          version,
          license: item.license ?? license,
          homepage: item.homepage,
          directory,
        });
      }
    }
  }
  return entries;
}

export function main(): void {
  const result = spawnSync("pnpm", ["licenses", "list", "--prod", "--json"], {
    encoding: "utf8",
  });
  if (result.error || result.status !== 0) {
    console.error(`pnpm licenses list failed: ${result.error ?? result.stderr}`);
    process.exitCode = 1;
    return;
  }
  try {
    const entries = flattenPnpmOutput(JSON.parse(result.stdout));
    const notices = buildNotices(entries, readLicenceFile);
    if (!notices.ok) {
      for (const label of notices.missing) console.error(`Unresolvable licence: ${label}`);
      process.exitCode = 1;
      return;
    }
    mkdirSync("public", { recursive: true });
    writeFileSync("public/third-party-notices.txt", notices.text, "utf8");
  } catch (error) {
    console.error(`Cannot generate third-party notices: ${String(error)}`);
    process.exitCode = 1;
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) main();
